[
  {
    name: "Pitta",
    subtitle: "The Energy of Digestion and Metabolism",
    elements: "Fire, Water",
    description: "Pitta types have many of the qualities of fire. Fire is hot, penetrating, sharp and agitating. Similarly, pitta people have warm bodies, penetrating ideas and sharp intelligence. When out of balance, they can become very agitated and short-tempered. The pitta body type is one of medium height and build, with ruddy or coppery skin. They may have many moles and freckles. Their skin is warm and less wrinkled than vata skin. Their hair tends to be silky and they often experience premature graying or hair loss. Their eyes are of medium size and the conjunctiva is moist. The nose is sharp and the tip tends to be reddish.

    Those with pitta-dominant constitutions have a strong metabolism, good digestion and strong appetites. They like plenty of food and liquids and tend to love hot spices and cold drinks. However, their constitution is balanced by sweet, bitter and astringent tastes. Pitta people’s sleep is sound and of medium duration. They produce large quantities of urine and feces, which tend to be yellowish, soft and plentiful. They perspire easily and their hands and feet stay warm. Pitta people have a lower tolerance for sunlight, heat and hard physical work.

    Mentally, pitta types are alert and intelligent and have good powers of comprehension. However, they are easily agitated and aggressive and tend toward hate, anger and jealousy when imbalanced. In the external world, pitta people like to be leaders and planners and seek material prosperity. They like to exhibit their wealth and possessions. Pitta people tend to have diseases involving the fire principle such as fevers, inflammatory diseases and jaundice. Common symptoms include skin rashes, burning sensation, ulceration, fever, inflammations or irritations such as conjunctivitis, colitis or sore throats.

    Since the attributes of pitta are oily, hot, light, mobile, dispersing and liquid, an excess of any of these qualities aggravates pitta. Summer is a time of heat, the pitta season. Sunburn, poison ivy, prickly heat and short tempers are common. These kinds of pitta disorders tend to calm down as the weather gets cooler. The diet and lifestyle changes emphasize coolness—cool foods, avoidance of chilies and spices, and cool climates. People with excessive pitta need to exercise at the coolest part of the day.",
    diet: "General food guidelines for pacifying pitta include avoiding sour, salty and pungent foods. Vegetarianism is best for pitta people and they should refrain from eating meat, eggs, alcohol and salt. To help calm their natural aggressiveness and compulsiveness, it is beneficial to incorporate sweet, cooling and bitter foods and tastes into their diets.

    Barley, rice, oats and wheat are good grains for pitta dominant individuals and vegetables should form a substantial part of their diet. Tomatoes, radishes, chilies, garlic and raw onions should all be avoided. In fact, any vegetable that is too sour or hot will aggravate pitta, but most other vegetables will help to calm it. Daikon radishes are cleansing for the liver when pitta is in balance but should be avoided otherwise. Salads and raw vegetables are good for pitta types in the spring and summer as are any sweet fruits. Sour fruits should be avoided with the exception of limes, used sparingly.

    Animal foods, especially seafood and eggs, should only be taken in moderation by pitta types. Chicken, turkey, rabbit and venison are all right. All legumes except red and yellow lentils are good in small amounts, with black lentils, chickpeas and mung beans being the best.

    Most nuts and seeds have too much oil and are heating for pitta. However, coconut is cooling and sunflower and pumpkin seeds are all right occasionally. Small amounts of coconut, olive and sunflower oils are also good for pitta. Sweet dairy products are good and include milk, unsalted butter, ghee and soft, unsalted cheeses. Yogurt can be used if it is blended with spices, a little sweetener and water. In fact, pitta people can use a sweetener better than the other two doshas because it relieves pitta. However, they should avoid hot spices, using cardamom, cinnamon, coriander, fennel and turmeric predominantly, with small amounts of cumin and black pepper.

    Coffee, alcohol and tobacco should be completely avoided although the occasional beer may be relaxing for a pitta person. Black tea may also be used occasionally with a little milk and a pinch of cardamom.",
    image: "https://images.wemystic.com.br/repo/pita2.jpg"
  },
  {
    name: "Vata",
    subtitle: "The Energy of Movement",
    elements: "Air, Ether",
    description: "Vata provides the essential motion for all bodily processes and is extremely vital for health. On an annual basis, vāta is most prominent in the fall and at the change of seasons, and these are the most important times to be careful of diet and lifestyle. One purpose of lifestyle considerations is stabilize this motion. Routine is very useful in assisting the vata individual to effectively ground all this moving energy.

    A person with vata predominant is blessed with a quick mind, flexibility and creativity. Mentally, they usually grasp concepts quickly but then forget them just as quickly. Alert, restless and very active, vata people walk, talk and think fast, but are easily fatigued. They tend to have less willpower, confidence, boldness and tolerance for fluctuation than other types and often feel unstable and ungrounded. When unbalanced, vata types may become fearful, nervous and anxious. In the external world, vata types tend to earn money quickly and spend it quickly. They are not good planners and as a consequence may suffer economic hardship.

    Vata types have variable appetite and digestion. They are often attracted to astringent foods like salad and raw vegetables, but their constitution is balanced by warm, cooked foods and sweet, sour and salty tastes. With a tendency to produce little urine, their feces are often hard, dry and small in size and quantity.

    Vata resides in the colon, as well as the brain, ears, bones, joints, skin and thighs. Vata people are more susceptible to diseases involving the air principle, such as emphysema, pneumonia and arthritis. Other common vata disorders include flatulence, tics, twitches, aching joints, dry skin and hair, nerve disorders, constipation, and mental confusion. Vata in the body tends to increase with age as is exhibited by the drying and wrinkling of the skin.

    Since the attributes of vata are dry, light, cold, rough, subtle, mobile and clear, any of these qualities in excess can cause imbalance. Frequent travel, especially by plane, loud noises, continual stimulation, drugs, sugar and alcohol all derange vata, as does exposure to cold and cold liquids and foods. Like the wind, vata types have a hard time becoming and staying grounded. Routine is difficult but essential if vata is to be lowered and controlled. It is best for vata types to go to bed by 10 PM as they need more rest than the other types. In general, people with excessive vata respond most rapidly to warm, moist, slightly oily, heavy foods. Steam baths, humidifiers and moisture in general are helpful. Daily oil massage before bath or shower is also recommended.",
    diet: "General food guidelines for decreasing vata include warm, well-cooked, unctuous foods. One should have small meals three or four times a day and may snack as needed while maintaining a two hour gap between each meal. Regularity in meal times is important for vata. Those with vata-dominant constitutions do well with one- pot meals such as soups, stews and casseroles. They can use more oil in cooking their foods than the other two doshas and experience better digestion if they limit their intake of raw foods.

    Well-cooked oats and rice are good for vata because they are not too drying when cooked with plenty of water and butter or ghee. While cooked vegetables are best for vata, the occasional salad with a good oily or creamy dressing is all right. Nightshades—tomatoes, potatoes, eggplants and peppers—as well as spinach should be avoided if the vata person has stiff, aching joints or muscles. Sweet, ripe and juicy fruits are good for vata. The astringent and drying fruits, such as cranberries, pomegranates and raw apples, should be avoided. Fruit should always be eaten by itself on an empty stomach.

    Many vata people can satisfy their need for protein by judicious use of dairy products, but can also use eggs, chicken, turkey, fresh fish and venison if they wish. Legumes are difficult to digest and should be consumed in limited quantity by those trying to pacify vata. The legumes should be the split type and soaked before cooking. Cooking them with a little oil and spices, such as turmeric, cumin, coriander, ginger, garlic and hing (asafoetida), will help prevent vata from being disturbed.

    All nuts and seeds are good for vata, but are best used as butters or milks. Ten almonds, soaked in water overnight with skins removed the next morning, are a satisfying early morning food. Sesame oil is warming for vata, but all oils are good. All dairy products are good for vata with hard cheese being eaten sparingly. All spices are good, but should not be overused. Vatas can have half a glass of wine, diluted with water, during or after a meal. Since vata people tend to be prone to addiction, they should avoid sugar, caffeine and tobacco. Intensity itself can be intoxicating to vata, so one should seek relaxation and meditation to reduce vata.",
    image: "http://images.wemystic.com.br/repo/vata.jpg"
  },
  {
    name: "Kapha",
    subtitle: "The Energy of Lubrication",
    elements: "Earth, Water",
    description: "Kapha types are blessed with strength, endurance and stamina. In balance, they tend to have sweet, loving dispositions and be stable and grounded. Their skin is oily and smooth. Physically, kapha people may gain weight easily and have a slow metabolism. They tend to shun exercise. They have thick skin and their bodies and muscles are well developed. Their eyes are large and attractive with thick, long lashes and brows. Kapha people evacuate slowly and feces tend to be soft, pale and oily. Perspiration is moderate. Sleep is deep and prolonged. Kapha types are attracted to sweet, salty and oily foods, but their constitutions are most balanced by bitter, astringent and pungent tastes.

    Psychologically, kapha people tend to be calm, tolerant and forgiving. However, they may become lethargic. While they may be slow to comprehend, their long term memory is excellent. When out of balance, kaphas tend to experience greed, envy, attachment and possessiveness. In the external world, kapha tendencies toward groundedness, stability and attachment help them to earn and hold onto money.

    They are more likely to have diseases connected to the water principle such as flu, sinus congestion, and other diseases involving mucous. Sluggishness, excess weight, diabetes, water retention, and headaches are also common. Kapha can become more aggravated as the moon gets full because there is a tendency for water retention at that time. Winter is the time of greatest kapha accumulation and following the kapha-balancing dietary and lifestyle changes are most important during that season.",
    diet: "Dietary guidelines for kapha people stress bitter, astringent and pungent tastes. They actually need foods that will invigorate their minds while limiting their overall consumption of food. They should avoid dairy products and fats of any kind, especially fried or greasy foods.

    Those with kapha dominant constitutions need less grain than pitta or vata constitutions with buckwheat and millet (more heating) being optimal grains for them followed by barley, rice and corn. Roasted or dry cooked grains are best. All vegetables are good for kapha but one should emphasize leafy greens and vegetables grown above ground more than root vegetables while avoiding very sweet, sour or juicy vegetables. Generally kapha people can eat raw vegetables although steamed or stir-fried are easier to digest. Very sweet or sour fruits should be avoided with the more astringent and drying fruits being preferable such as apples, apricots, cranberries, mangoes, peaches and pears.

    Only rarely do kapha people need animal foods and, when they do, it should be dry cooked—baked, roasted, broiled—never fried. They could eat chicken, eggs, rabbit, seafood and venison. As their bodies do not require large amounts of protein, they also should not overeat legumes although these are better for them than meat because of the lack of fat. Black beans, mung beans, pinto beans and red lentils are best for kapha types.

    The heavy qualities of nuts and seeds aggravate kapha as does the oil in them. Occasional sunflower and pumpkin seeds are all right. Almond, corn, safflower or sunflower oils can be used in small amounts as well. The same holds true for dairy products: in general, kapha people should avoid the heavy, cooling, sweet qualities of dairy. A little ghee for cooking and some consumption of goat’s milk is good for kapha types.

    Since kapha people should avoid sweets, the only sweetener they should use is raw honey, which is heating. However, they can use all spices, except salt, with ginger and garlic being best for them. A person whose dominant dosha is kapha and who has very little influence from the other two doshas can benefit from the occasional use of stimulants such as coffee and tea. They are also not as harmed by tobacco and hard liquor. However, they really do not need alcohol at all. If they elect to use alcohol, wine is their best choice.",
    image: "https://www.urbanveda.com/gb/wp-content/uploads/2017/07/Kapha-dosha.jpg"
  }
].each do |attributes|
  Dosha.find_or_create_by(attributes)
end